### ISSUE TITLE
是否支持自定义ip和port来启动服务

### ISSUE THREAD

**Issue by Tovi163** [opendatalab/LabelLLM#28]
是否支持自定义ip和port来启动服务，以及如何启动

**Comment by lacia-hIE** [comment]
可自行修改 [docker-compose.yaml](https://github.com/opendatalab/LabelLLM/blob/main/docker-compose.yaml)

**Comment by Tovi163** [comment]
> 可自行修改 [docker-compose.yaml](https://github.com/opendatalab/LabelLLM/blob/main/docker-compose.yaml)

@lacia-hIE 修改了yaml但未生效，依然提示是9000和9001

**Comment by lacia-hIE** [comment]
请展示一下修改的  `docker-compose.yaml`

**Comment by lacia-hIE** [comment]
我建议可以修改为  

```
minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '8000:9000'
      - '8001:9001'
```

其它请参考 [docker doc](https://docs.docker.com/guides/docker-concepts/running-containers/publishing-ports/)
